
name: Continous Deployment

on:
  push:
    branches: 
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install dependencies
      run: yarn install --skip-integrity-check --non-interactive --no-progress

    - name: Deploy to netlify
      uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist/