name: Continous Integration

on:
 push:
    branches: [master, elaine]
 pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: TypeScript check
        run: yarn lint:tsc

      - name: Eslint check
        run: yarn lint:script

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@elaine

      # https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Unit test
        run: yarn test:unit:ci
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
    
  e2e_tests:
    name: E2E test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: E2E test
        run: yarn test:e2e:ci
  